name: Commitlint

on: [push, pull_request]

jobs:
    commitlint:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Set up Node.js 16
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Install required dependencies
              run: |
                  sudo apt update
                  sudo apt install -y git

            - name: Print versions
              run: |
                  git --version
                  node --version
                  npm --version

            - name: Install commitlint
              run: |
                  npm install conventional-changelog-conventionalcommits
                  npm install commitlint@latest
                  npm install @commitlint/config-conventional

            - name: Create commitlint config file
              run: |
                  echo "module.exports = {extends: ['@commitlint/config-conventional']}" > commitlint.config.js

            - name: Validate current commit (last commit) with commitlint
              if: github.event_name == 'push'
              run: npx commitlint --from HEAD~1 --to HEAD --verbose

            - name: Validate PR commits with commitlint
              if: github.event_name == 'pull_request'
              run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
